/**
 * src/types/index.ts
 * Central type definitions for the Aethra roleplay application.
 * All shared interfaces and enums are declared here to ensure consistency
 * across components, services, and the Electron main process.
 */

/* ── Chat & sessions ──────────────────────────────────────────────────── */

/** Identifies who authored a message in the conversation. */
export type MessageRole = 'user' | 'assistant' | 'system'

/**
 * A single message within a roleplay session.
 */
export interface Message {
  /** Unique identifier for the message. */
  id: string
  /** Who sent this message. */
  role: MessageRole
  /** Campaign character ID the user selected when writing this message, if any. */
  characterId?: string
  /** Character name snapshot captured when the message was created, if any. */
  characterName?: string
  /** The text content of the message. */
  content: string
  /** Unix timestamp (ms) when the message was created. */
  timestamp: number
}

/**
 * A roleplay session, analogous to a conversation thread.
 * Contains metadata and the full message history.
 */
export interface Session {
  /** Unique identifier for the session. */
  id: string
  /** Human-readable title shown in the sidebar. */
  title: string
  /** Ordered list of messages exchanged in this session. */
  messages: Message[]
  /** Unix timestamp (ms) when the session was created. */
  createdAt: number
  /** Unix timestamp (ms) of the most recent activity. */
  updatedAt: number
}

/**
 * A persisted campaign file containing multiple sessions.
 */
export interface Campaign {
  /** Unique identifier for the campaign. */
  id: string
  /** Human-readable campaign name. */
  name: string
  /** Short descriptive summary of the campaign. */
  description: string
  /** Ordered list of sessions that belong to the campaign. */
  sessions: Session[]
  /** Unix timestamp (ms) when the campaign was created. */
  createdAt: number
  /** Unix timestamp (ms) of the most recent campaign update. */
  updatedAt: number
}

/**
 * Stored campaign plus its containing folder path.
 */
export interface CampaignFileHandle {
  /** Absolute filesystem path of the campaign folder. */
  path: string
  /** Parsed campaign content loaded from that file. */
  campaign: Campaign
}

/**
 * Lightweight campaign metadata shown in the launcher.
 */
export interface CampaignSummary {
  /** Unique campaign identifier. */
  id: string
  /** Display name shown in the campaign picker. */
  name: string
  /** Short descriptive summary shown in the campaign picker. */
  description: string
  /** Absolute filesystem path of the stored campaign folder. */
  path: string
  /** Unix timestamp (ms) of the most recent campaign update. */
  updatedAt: number
  /** Total sessions currently stored in the campaign. */
  sessionCount: number
}

/**
 * A persisted character profile stored within a campaign's characters folder.
 */
export interface CharacterProfile {
  /** Unique character identifier. */
  id: string
  /** Display name shown in the characters modal. */
  name: string
  /** Filesystem folder name allocated for this character. */
  folderName: string
  /** Character role or archetype shown in the character list. */
  role: string
  /** Character gender identity used in prompts and editor defaults. */
  gender: 'male' | 'female' | 'non-specific'
  /** Character pronouns used in prompts and editor defaults. */
  pronouns: 'he/him' | 'she/her' | 'they/them'
  /** Physical description and presentation details. */
  description: string
  /** Personality traits and temperament notes. */
  personality: string
  /** Guidance for the way this character speaks. */
  speakingStyle: string
  /** Current objectives, motivations, or priorities. */
  goals: string
  /** Which participant controls this character in play. */
  controlledBy: 'ai' | 'user'
  /** Unix timestamp (ms) when the character was created. */
  createdAt: number
  /** Unix timestamp (ms) when the character was last updated. */
  updatedAt: number
}

/**
 * A single message in the format expected by OpenAI-compatible chat APIs.
 * Used when building the payload sent to the AI server.
 */
export interface ChatMessage {
  /** Author role. */
  role: 'user' | 'assistant' | 'system'
  /** Text content. */
  content: string
}

/**
 * Token usage reported by an OpenAI-compatible server.
 */
export interface TokenUsage {
  /** Tokens consumed by the prompt portion of the request. */
  promptTokens: number
  /** Tokens generated by the completion. */
  completionTokens: number
  /** Total tokens reported for the request. */
  totalTokens: number
}

/**
 * A single debug event captured around AI server traffic.
 */
export interface AiDebugEntry {
  /** Stable identifier for list rendering. */
  id: string
  /** Unix timestamp in milliseconds when the event was recorded. */
  timestamp: number
  /** High-level category for the event. */
  direction: 'request' | 'response' | 'info' | 'error'
  /** Short event label. */
  label: string
  /** Structured payload recorded for inspection. */
  payload: unknown
}

/* ── Settings ─────────────────────────────────────────────────────────── */

/** Supported visual modes for themes. */
export type ThemeMode = 'dark' | 'light'

/** Supported chat bubble text size presets. */
export type ChatTextSize = 'small' | 'medium' | 'large' | 'extra-large'

/** Public theme token names allowed in built-in or imported theme files. */
export type ThemeTokenName =
  | 'app-bg'
  | 'panel-bg'
  | 'surface-bg'
  | 'surface-bg-emphasis'
  | 'surface-bg-selected'
  | 'surface-bg-user-message'
  | 'surface-bg-accent'
  | 'surface-bg-accent-hover'
  | 'surface-bg-overlay'
  | 'border-color'
  | 'border-color-accent'
  | 'text-color-primary'
  | 'text-color-secondary'
  | 'text-color-muted'
  | 'text-color-on-accent'
  | 'text-color-brand'
  | 'scrollbar-thumb'
  | 'scrollbar-thumb-hover'
  | 'shadow-panel'
  | 'shadow-modal'

/**
 * A downloadable/importable theme definition.
 * Tokens are partial so custom themes can override only the values they need.
 */
export interface ThemeDefinition {
  /** Unique identifier used in persisted settings and theme selection. */
  id: string
  /** Human-readable theme name shown in the settings modal. */
  name: string
  /** Declares whether the theme is primarily light or dark. */
  mode: ThemeMode
  /** Token override map applied to the semantic CSS variable layer. */
  tokens: Partial<Record<ThemeTokenName, string>>
}

/**
 * Window chrome state mirrored from Electron into the renderer.
 */
export interface WindowControlsState {
  /** Host operating system reported by the Electron main process. */
  platform: 'darwin' | 'win32' | 'linux'
  /** True when the window is currently maximized. */
  isMaximized: boolean
}

/**
 * A configured AI server the user can connect to.
 * Stored in AppSettings and persisted to userData/settings.json.
 */
export interface ServerProfile {
  /** Unique identifier. */
  id: string
  /** Display name shown in the UI (e.g. "LM Studio"). */
  name: string
  /** Base URL of the OpenAI-compatible API (e.g. http://localhost:1234/v1). */
  baseUrl: string
  /** API key — most local servers accept any non-empty string. */
  apiKey: string
}

/**
 * A saved model preset associated with a server.
 */
export interface ModelPreset {
  /** Unique identifier. */
  id: string
  /** ID of the ServerProfile this model belongs to. */
  serverId: string
  /** Display name shown in the UI (e.g. "Llama 3 8B"). */
  name: string
  /** Model slug sent to the API (e.g. "llama3", "local-model"). */
  slug: string
  /** Optional approximate context window size for UI budgeting. */
  contextWindowTokens?: number
  /** Optional sampling temperature used for chat completions. */
  temperature?: number
}

/**
 * A model discovered live from a configured AI server.
 */
export interface AvailableModel {
  /** Stable ID from the upstream server model listing. */
  id: string
  /** ID of the ServerProfile the model belongs to. */
  serverId: string
  /** Human-readable display name. */
  name: string
  /** Model slug sent to the API. */
  slug: string
  /** Optional approximate context window size for UI budgeting. */
  contextWindowTokens?: number
}

/**
 * Persisted application settings.
 * Loaded from / saved to <userData>/settings.json by the main process.
 */
export interface AppSettings {
  /** All configured server profiles. */
  servers: ServerProfile[]
  /** All saved model presets. */
  models: ModelPreset[]
  /** ID of the server profile currently selected as default. */
  activeServerId: string | null
  /** Model slug currently selected as default. */
  activeModelSlug: string | null
  /** System prompt prepended to each chat request. */
  systemPrompt: string
  /** Selected chat bubble text size preset. */
  chatTextSize: ChatTextSize
  /** Selected visual theme ID. Built-ins and custom themes share the same namespace. */
  activeThemeId: string
  /** Imported user theme definitions. */
  customThemes: ThemeDefinition[]
}
